[package]
name = "rivaren-app"
version.workspace = true
edition.workspace = true

[[bin]]
name = "rivaren"
path = "src/main.rs"

[dependencies]
rivaren-core.workspace = true
rivaren-world.workspace = true
rivaren-compression.workspace = true
rivaren-meshing.workspace = true
rivaren-render.workspace = true
rivaren-lighting.workspace = true
rivaren-entities.workspace = true
rivaren-physics.workspace = true
rivaren-gameplay.workspace = true
rivaren-netcode.workspace = true
rivaren-mods.workspace = true
rivaren-audio.workspace = true
rivaren-ui.workspace = true
wgpu.workspace = true
winit.workspace = true
pollster.workspace = true
rayon.workspace = true
crossbeam.workspace = true
flume.workspace = true
glam.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
parking_lot.workspace = true
bytemuck.workspace = true
